name: Zed Nightly Build

on:
  schedule:
    # Runs every night at midnight UTC
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        graphics_backend: [vulkan]
        include:
          - graphics_backend: vulkan
            build_artifact_name: zed-release-vulkan
            build_flags: ""

    steps:
      - name: Configure Git long paths
        run: |
          git config --system core.longpaths true
      
      - name: Configure Windows long paths
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
      
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main
      
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasip1

      - name: Work around spurious network errors in curl 8.0
        run: |
          if rustc +nightly --version --verbose | grep -q '^release: 1\.7[01]\.'; then
            echo CARGO_HTTP_MULTIPLEXING=false >> $GITHUB_ENV
          fi
      
      - name: Configure Rust caching
        uses: Swatinem/rust-cache@v2.7.3
        with:
          key: vulkan
      
      - name: Build release binary
        env:
          RUSTFLAGS: ${{ matrix.build_flags }}
        run: cargo build --release -j ${{ env.NUM_CORES }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build_artifact_name }}
          path: target/release/zed.exe
          retention-days: 5
  
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Generate release timestamp
        id: release_date
        run: echo "RELEASE_TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      - name: Package release build
        run: |
          mkdir -p zed-release-vulkan
          mv artifacts/zed-release-vulkan/zed.exe zed-release-vulkan/
          zip -r zed-windows-vulkan.zip zed-release-vulkan/*
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: Zed Nightly ${{ env.RELEASE_TIMESTAMP }}
          tag_name: nightly-${{ env.RELEASE_TIMESTAMP }}
          draft: false
          make_latest: true
          body: |
            Nightly build of Zed editor for Windows
            - Vulkan backend: Standard graphics backend
          files: |
            zed-windows-vulkan.zip
